# Generated by Django 4.1.2 on 2022-10-05 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_month', models.CharField(max_length=150, verbose_name='Месяц')),
                ('number_of_the_month', models.IntegerField(verbose_name='Номер по порядку')),
            ],
        ),
        migrations.CreateModel(
            name='week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_week', models.CharField(max_length=100, verbose_name='Неделя')),
                ('number_of_the_week', models.IntegerField(verbose_name='Неделя')),
            ],
        ),
    ]
