# Generated by Django 4.1.2 on 2022-10-05 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='month',
            options={'ordering': ['title_month'], 'verbose_name': 'Месяц', 'verbose_name_plural': 'Месяцы'},
        ),
        migrations.AlterModelOptions(
            name='week',
            options={'ordering': ['title_week'], 'verbose_name': 'Неделя', 'verbose_name_plural': 'Недели'},
        ),
    ]
