# Generated by Django 4.1.2 on 2022-10-05 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0002_alter_month_options_alter_week_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='month',
            options={'ordering': ['number_of_the_month'], 'verbose_name': 'Месяц', 'verbose_name_plural': 'Месяцы'},
        ),
        migrations.AddField(
            model_name='month',
            name='amount_of_days',
            field=models.IntegerField(default=1, verbose_name='Количество дней'),
            preserve_default=False,
        ),
    ]
